In [1]:
import pandas as pd
import os
import re

In [2]:
top_games = pd.read_csv('game_names_with_appids_to_notebook.csv', sep=',')

In [3]:
player_counts = []
folder = 'steam_player_charts'
for filename in os.listdir(folder):
    if filename.endswith('.csv'):
        df = pd.read_csv(os.path.join(folder, filename), sep=';', index_col=0)
        df.index = pd.to_datetime(df.index)
        player_counts.append(df)

player_counts_df = pd.concat(player_counts, axis=1)
player_counts_df.reset_index(inplace=True)

player_counts_df.describe()

C:\Users\magda\AppData\Local\Temp\ipykernel_10676\1684145044.py:9: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  player_counts_df = pd.concat(player_counts, axis=1)
C:\Users\magda\AppData\Local\Temp\ipykernel_10676\1684145044.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  player_counts_df.reset_index(inplace=True)

,DateTime,Dota 2,Counter-Strike 2,PUBG: BATTLEGROUNDS,Hollow Knight: Silksong,ARC Raiders,Monster Hunter Wilds,Marvel Rivals,Battlefield™ 6,Battlefield™ 6 Open Beta,...,Team Fortress 2,No Man's Sky,RimWorld,Destiny 2,Hades II,Red Dead Redemption 2,EA SPORTS FC 25,FragPunk,EA SPORTS FC™ 26,RV There Yet?
count,6813,5.321000e+03,5.117000e+03,3.345000e+03,253.000000,197.000000,4.410000e+02,525.000000,217.000000,16.000000,...,6053.000000,3578.000000,3641.000000,2418.000000,739.000000,2353.000000,595.000000,435.000000,232.000000,206.000000
mean,2017-01-15 00:00:00,6.425632e+05,7.424138e+05,7.084541e+05,56825.727273,253658.634518,9.903483e+04,170925.285714,145848.755760,234664.625000,...,66333.861887,10624.257686,19646.244713,71824.639785,11271.054127,35532.160646,50760.216807,6967.294253,68289.896552,15736.640777
min,2007-09-19 00:00:00,1.940000e+02,2.040000e+02,1.000000e+00,8512.000000,80918.000000,1.306900e+04,77002.000000,38310.000000,2757.000000,...,3475.000000,1.000000,2.000000,7481.000000,1437.000000,10242.000000,9382.000000,1277.000000,42971.000000,5099.000000
25%,2012-05-18 00:00:00,5.945100e+05,4.862880e+05,4.028930e+05,12259.000000,140395.000000,2.528600e+04,99525.000000,54134.000000,8602.750000,...,53630.000000,4496.250000,11509.000000,43003.500000,3289.000000,23328.000000,16223.500000,1950.500000,60626.500000,7861.000000
50%,2017-01-15 00:00:00,6.678240e+05,6.542260e+05,5.757500e+05,19042.000000,264673.000000,3.808300e+04,125070.000000,76830.000000,302594.500000,...,64581.000000,8369.000000,19189.000000,65602.500000,5873.000000,34378.000000,61529.000000,2647.000000,66575.000000,10705.500000
75%,2021-09-14 00:00:00,7.778070e+05,1.074059e+06,7.453520e+05,35060.000000,346396.000000,7.087100e+04,182579.000000,177449.000000,370981.250000,...,79703.000000,13015.000000,25020.000000,88807.250000,11586.000000,45227.000000,76560.000000,4797.000000,74912.000000,18951.500000
max,2026-05-14 00:00:00,1.291328e+06,1.862531e+06,3.257248e+06,587150.000000,481966.000000,1.384608e+06,644269.000000,747440.000000,521079.000000,...,253997.000000,212604.000000,96040.000000,316750.000000,112947.000000,99993.000000,110026.000000,113946.000000,100753.000000,100002.000000
std,NaN,2.321138e+05,4.693848e+05,5.447466e+05,102666.719133,111376.284801,1.948096e+05,110882.617371,144466.390767,192540.224647,...,26410.939158,11568.077620,10781.340679,43017.479406,16328.703775,14264.752608,30216.457294,14366.280792,11608.805155,13914.901613

In [4]:
for col in player_counts_df.columns[1:]:
    if col not in top_games['name'].values:
        player_counts_df.drop(columns=col, inplace=True)

In [5]:
twitch_counts = []
folder = '2025_twitch_watch_charts'
for filename in os.listdir(folder):
    if filename.endswith('.csv'):
        match = re.search(r'\d+', filename)
        appid = match.group()

        df = pd.read_csv(os.path.join(folder, filename), sep=';', index_col=0)
        df.index = pd.to_datetime(df.index)
        df.columns = [appid]
        twitch_counts.append(df)

twitch_counts_df = pd.concat(twitch_counts, axis=1)
twitch_counts_df.reset_index(inplace=True)
twitch_counts_df.describe()

C:\Users\magda\AppData\Local\Temp\ipykernel_10676\3959714169.py:13: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  twitch_counts_df = pd.concat(twitch_counts, axis=1)

,DateTime,1030300,1085660,1086940,1091500,1145350,1158310,1172470,1172710,1174180,...,3949040,413150,438100,440,489830,552990,553850,570,578080,899770
count,3956,2641.000000,3285.000000,2530.000000,3.931000e+03,1253.000000,2399.000000,2658.000000,1361.000000,3495.000000,...,208.000000,3804.000000,3160.000000,3956.000000,1845.000000,3956.000000,1087.000000,3.956000e+03,3536.000000,3014.000000
mean,2020-12-14 12:00:00,1175.097312,19095.998478,5253.765217,4.543978e+03,1668.592977,2063.318466,82145.359669,2410.629684,9325.761373,...,14948.437500,4230.119611,10439.440190,1454.894085,1767.086721,5420.345046,5380.191352,1.306174e+05,53263.286482,1504.383543
min,2015-07-17 00:00:00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,2018-03-31 18:00:00,0.000000,8885.000000,62.000000,0.000000e+00,0.000000,288.000000,40747.750000,0.000000,1345.000000,...,1742.250000,1485.750000,5271.000000,598.000000,609.000000,2478.000000,737.000000,7.091875e+04,23908.750000,41.000000
50%,2020-12-14 12:00:00,0.000000,13028.000000,427.500000,6.250000e+02,144.000000,742.000000,64905.000000,0.000000,6517.000000,...,5716.000000,2718.000000,7676.000000,824.000000,988.000000,4546.500000,1640.000000,1.003965e+05,38960.000000,139.000000
75%,2023-08-30 06:00:00,3.000000,19139.000000,5135.250000,2.780000e+03,814.000000,1945.500000,105030.250000,485.000000,10907.000000,...,16281.750000,4612.500000,11871.500000,1270.250000,2156.000000,7029.750000,3456.000000,1.530215e+05,66877.750000,481.750000
max,2026-05-15 00:00:00,359067.000000,523610.000000,481973.000000,1.143961e+06,99194.000000,64778.000000,666868.000000,221716.000000,382860.000000,...,94901.000000,99549.000000,127919.000000,82315.000000,23542.000000,62804.000000,151927.000000,1.719828e+06,597309.000000,262876.000000
std,NaN,9857.214599,31743.410716,17588.563477,3.310458e+04,6681.847300,4809.956316,62431.800031,13173.874694,15274.884491,...,21485.882897,6128.483430,10955.472889,3253.023586,1940.886584,4104.362452,13393.490089,1.053281e+05,45950.147376,9033.042003

In [6]:
player_counts_df = player_counts_df[(player_counts_df['DateTime'] >= '2025-01-01') & (player_counts_df['DateTime'] <= '2025-12-31')]
twitch_counts_df = twitch_counts_df[(twitch_counts_df['DateTime'] >= '2025-01-01') & (twitch_counts_df['DateTime'] <= '2025-12-31')]

In [7]:
player_counts_df.describe()

,DateTime,Dota 2,Counter-Strike 2,PUBG: BATTLEGROUNDS,Hollow Knight: Silksong,ARC Raiders,Monster Hunter Wilds,Marvel Rivals,Battlefield™ 6,Schedule I,...,Team Fortress 2,No Man's Sky,RimWorld,Destiny 2,Hades II,Red Dead Redemption 2,EA SPORTS FC 25,FragPunk,EA SPORTS FC™ 26,RV There Yet?
count,365,365.000000,3.650000e+02,3.650000e+02,119.000000,63.000000,3.070000e+02,365.000000,83.000000,283.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,301.000000,98.000000,72.000000
mean,2025-07-02 00:00:00,678242.928767,1.505722e+06,7.023766e+05,105199.991597,350547.333333,1.261558e+05,175523.087671,280169.325301,56135.636042,...,55515.175342,20485.495890,34898.953425,36046.460274,12399.449315,50466.021918,58869.873973,9189.853821,68916.724490,25992.958333
min,2025-01-01 00:00:00,528819.000000,1.158622e+06,4.267930e+05,16748.000000,253486.000000,1.306900e+04,77002.000000,83650.000000,10702.000000,...,31748.000000,6606.000000,23242.000000,12577.000000,2065.000000,32411.000000,14199.000000,1507.000000,42971.000000,8581.000000
25%,2025-04-02 00:00:00,588377.000000,1.388160e+06,6.574890e+05,25756.000000,313020.000000,2.603050e+04,102527.000000,138584.500000,15902.500000,...,50344.000000,10994.000000,27145.000000,24488.000000,3085.000000,43215.000000,30586.000000,2417.000000,59445.000000,13226.500000
50%,2025-07-02 00:00:00,644244.000000,1.492628e+06,6.975200e+05,40769.000000,348832.000000,4.396900e+04,130506.000000,237015.000000,21515.000000,...,55186.000000,14845.000000,30335.000000,30988.000000,5040.000000,48791.000000,66749.000000,3590.000000,67378.500000,20954.500000
75%,2025-10-01 00:00:00,766441.000000,1.617900e+06,7.498580e+05,120488.000000,385181.500000,1.004880e+05,194063.000000,397041.500000,38003.000000,...,58499.000000,23371.000000,34951.000000,43899.000000,15250.000000,54878.000000,78492.000000,7917.000000,77320.750000,28357.000000
max,2025-12-31 00:00:00,961289.000000,1.862531e+06,1.347327e+06,587150.000000,481966.000000,1.384608e+06,644269.000000,747440.000000,459075.000000,...,103041.000000,110893.000000,96040.000000,108535.000000,112947.000000,99993.000000,109678.000000,113946.000000,100283.000000,100002.000000
std,NaN,105706.087923,1.479701e+05,7.949207e+04,134268.775259,52557.090495,2.280638e+05,110673.715345,157650.526431,87057.999882,...,9308.598373,16580.710925,13477.180633,16784.166160,17442.028087,10767.819431,25717.145523,16802.485506,13389.701285,18609.316849

In [8]:
twitch_counts_df.describe()

,DateTime,1030300,1085660,1086940,1091500,1145350,1158310,1172470,1172710,1174180,...,3949040,413150,438100,440,489830,552990,553850,570,578080,899770
count,365,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,73.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,3.650000e+02,365.000000,365.000000
mean,2025-07-02 00:00:00,6930.594521,14116.487671,5813.745205,5677.895890,2208.920548,1950.569863,38335.013699,8086.115068,14714.158904,...,30013.054795,3479.309589,8513.980822,852.356164,1204.123288,5121.630137,3210.624658,1.306051e+05,32617.690411,2998.063014
min,2025-01-01 00:00:00,0.000000,2113.000000,1438.000000,601.000000,47.000000,71.000000,12445.000000,0.000000,3670.000000,...,2.000000,828.000000,4212.000000,221.000000,260.000000,1753.000000,758.000000,3.300800e+04,6231.000000,6.000000
25%,2025-04-02 00:00:00,0.000000,7060.000000,3203.000000,2079.000000,153.000000,294.000000,26941.000000,160.000000,6388.000000,...,7024.000000,2312.000000,6055.000000,480.000000,528.000000,3143.000000,1378.000000,7.117400e+04,19697.000000,98.000000
50%,2025-07-02 00:00:00,4.000000,9620.000000,4709.000000,3264.000000,526.000000,583.000000,33634.000000,1162.000000,8600.000000,...,18912.000000,3077.000000,7015.000000,614.000000,743.000000,4115.000000,1909.000000,1.144270e+05,27324.000000,238.000000
75%,2025-10-01 00:00:00,5843.000000,13291.000000,6739.000000,5392.000000,1730.000000,1785.000000,40454.000000,3232.000000,14583.000000,...,48037.000000,4218.000000,8314.000000,837.000000,1343.000000,5697.000000,3557.000000,1.610530e+05,36508.000000,1052.000000
max,2025-12-31 00:00:00,359067.000000,180101.000000,25476.000000,47309.000000,75911.000000,48775.000000,319643.000000,221716.000000,148641.000000,...,94901.000000,37737.000000,52068.000000,12380.000000,7141.000000,19606.000000,49607.000000,1.223548e+06,144592.000000,187806.000000
std,NaN,25488.167803,19821.416677,3919.758837,6473.772931,6279.682048,4714.342773,25148.903717,24315.926130,18798.781187,...,27085.461523,2415.068685,5549.995460,1099.230997,1159.523215,2824.219215,3932.308423,1.005390e+05,22101.286286,13927.821233

In [9]:
player_counts_df.set_index('DateTime', inplace=True)
start_dates = player_counts_df.apply(lambda col: col.first_valid_index())
late_starters = start_dates[start_dates > '2025-01-01']

In [10]:
late_starters

Hollow Knight: Silksong                     2025-09-04
ARC Raiders                                 2025-10-30
Monster Hunter Wilds                        2025-02-28
Battlefield™ 6                              2025-10-10
Schedule I                                  2025-03-24
Kingdom Come: Deliverance II                2025-02-04
Dispatch                                    2025-10-22
The Elder Scrolls IV: Oblivion Remastered   2025-04-22
Where Winds Meet                            2025-11-14
DYNASTY WARRIORS: ORIGINS                   2025-01-14
Digimon Story Time Stranger                 2025-10-02
Europa Universalis V                        2025-11-04
REMATCH                                     2025-06-16
inZOI                                       2025-03-28
Umamusume: Pretty Derby                     2025-06-25
Football Manager 26                         2025-11-04
Blue Protocol: Star Resonance               2025-10-09
DELTARUNE                                   2025-06-04
WUCHANG: Fallen Feathers                    2025-07-24
Mecha BREAK                                 2025-07-02
Shadowverse: Worlds Beyond                  2025-06-15
Dying Light: The Beast                      2025-09-18
Megabonk                                    2025-09-18
Clair Obscur: Expedition 33                 2025-04-24
Dune: Awakening                             2025-06-05
Grand Theft Auto V Enhanced                 2025-03-04
Bongo Cat                                   2025-03-05
Stellar Blade™                              2025-06-11
PEAK                                        2025-06-16
Borderlands® 4                              2025-09-11
Split Fiction                               2025-03-06
ELDEN RING NIGHTREIGN                       2025-05-29
Schedule I                                  2025-03-24
Escape from Duckov                          2025-10-16
R.E.P.O.                                    2025-02-26
FragPunk                                    2025-03-06
EA SPORTS FC™ 26                            2025-09-25
RV There Yet?                               2025-10-21
dtype: datetime64[us]

In [11]:
late_starters.count()

np.int64(38)

In [13]:
for game in top_games['name']:
    if game in late_starters.index:
        top_games.drop(top_games[top_games['name'] == game].index, inplace=True)
        try:
            player_counts_df.drop(columns=game, inplace=True)
        except KeyError:
            pass
        try:
            twitch_counts_df.drop(columns=game, inplace=True)
        except KeyError:
            pass

In [14]:
top_games.to_csv('game_names_with_appids_full_year.csv', index=False)
player_counts_df.to_csv('player_counts_full_year.csv')
twitch_counts_df.to_csv('twitch_counts_full_year.csv')