In [15]:
import pandas as pd
import os
import re

In [16]:
top_games = pd.read_csv('filtered_games_by_data24-07-26.csv', sep=',')

In [17]:
start_2025 = pd.to_datetime('2025-01-01')
end_2025 = pd.to_datetime('2025-12-31')

In [ ]:
player_counts = []
folder = 'player_counts_2025'
for filename in os.listdir(folder):
    if filename.endswith('.csv'):
        df = pd.read_csv(os.path.join(folder, filename), index_col = 0, sep = ';')
        df.index = pd.to_datetime(df.index)
        appid = re.search(r'\d+', filename).group()
        df.rename(columns={"Players" : int(appid)}, inplace=True)
        df.drop(columns=['Average Players'], inplace=True)
        df = df.loc[(df.index >= start_2025) & (df.index <= end_2025)]
        player_counts.append(df)

player_counts_df = pd.concat(player_counts, axis=1)
player_counts_df.describe()

,105600,107410,1085660,108600,1091500,1142710,1144200,1145360,1151340,1158310,...,739630,753640,767560,784080,892970,916440,945360,960090,961200,962130
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,36623.715068,13264.693151,36046.460274,30803.049315,44470.824658,29729.010959,10993.438356,5999.789041,11863.068493,24093.989041,...,23996.720548,1392.783562,1958.909589,1502.372603,31245.934247,6617.008219,8885.241096,11571.720548,2138.221918,6411.024658
std,6081.966448,2945.367462,16784.166160,8345.732673,12037.517250,6914.583815,6587.634218,3510.298148,2981.623984,7557.081044,...,6916.588069,324.877441,257.650468,696.784186,7525.420494,3824.754895,2325.584762,2771.561994,472.485505,2656.762059
min,24241.000000,8122.000000,12577.000000,20799.000000,24418.000000,21151.000000,4869.000000,2905.000000,7152.000000,17266.000000,...,13147.000000,873.000000,1325.000000,742.000000,18520.000000,2815.000000,4259.000000,7849.000000,1274.000000,2130.000000
25%,32135.000000,10978.000000,24488.000000,25007.000000,34417.000000,25195.000000,6996.000000,3801.000000,9968.000000,20311.000000,...,18348.000000,1158.000000,1768.000000,1013.000000,24922.000000,4295.000000,7404.000000,9682.000000,1802.000000,4319.000000
50%,36320.000000,12799.000000,30988.000000,28218.000000,43791.000000,27822.000000,8879.000000,4670.000000,11287.000000,22182.000000,...,22553.000000,1343.000000,1944.000000,1244.000000,30979.000000,5320.000000,8571.000000,10997.000000,2110.000000,5777.000000
75%,40934.000000,15076.000000,43899.000000,34194.000000,52779.000000,31747.000000,12479.000000,6829.000000,13041.000000,25189.000000,...,28544.000000,1610.000000,2147.000000,1803.000000,35769.000000,7272.000000,10428.000000,12598.000000,2468.000000,8078.000000
max,55462.000000,22317.000000,108535.000000,57886.000000,84236.000000,64399.000000,42490.000000,21221.000000,26373.000000,76719.000000,...,46942.000000,2538.000000,2762.000000,4603.000000,53576.000000,24689.000000,16298.000000,27736.000000,3502.000000,15266.000000

In [27]:
player_counts_df.isna().sum()

105600     0
107410     0
1085660    0
108600     0
1091500    0
          ..
916440     0
945360     0
960090     0
961200     0
962130     0
Length: 113, dtype: int64

In [54]:
twitch_counts = []
folder = '2025_twitch_views'
for filename in os.listdir(folder):
    if filename.endswith('.csv'):
        df = pd.read_csv(os.path.join(folder, filename), index_col=0)
        df.index = pd.to_datetime(df.index, format = 'mixed')
        appid = re.search(r'\d+', filename).group()
        df.rename(columns={"value" : int(appid)}, inplace=True)
        df.drop(columns=['chans'], inplace=True)
        twitch_counts.append(df)

twitch_counts_df = pd.concat(twitch_counts, axis=1)
twitch_counts_df.describe()

,105600,107410,1085660,108600,1091500,1142710,1144200,1145360,1151340,1158310,...,739630,753640,767560,784080,892970,916440,945360,960090,961200,962130
count,365.000000,365.000000,365.000000,365.00000,365.000000,365.000000,364.000000,365.00000,365.000000,365.000000,...,365.000000,365.000000,238.000000,348.000000,365.000000,360.00000,175.000000,365.000000,365.000000,365.000000
mean,622.468493,153.021918,4887.093151,2911.79726,1155.717808,497.049315,334.821429,183.79726,418.282192,516.391781,...,2652.227397,301.605479,144.172269,65.594828,899.117808,191.97500,579.582857,175.402740,390.841096,389.178082
std,858.982187,139.747769,5474.883863,3501.16570,1050.223665,458.101161,887.034083,487.82868,235.017476,1290.346671,...,2042.607115,454.800093,884.759916,92.909269,1093.923446,221.49846,1250.869708,329.830009,231.263127,697.802275
min,49.000000,33.000000,814.000000,482.00000,99.000000,87.000000,24.000000,25.00000,161.000000,24.000000,...,881.000000,28.000000,20.000000,19.000000,158.000000,20.00000,40.000000,21.000000,108.000000,23.000000
25%,183.000000,80.000000,2612.000000,1026.00000,496.000000,243.000000,62.000000,72.00000,288.000000,93.000000,...,1513.000000,93.000000,39.500000,28.000000,347.000000,59.75000,96.000000,47.000000,226.000000,74.000000
50%,306.000000,109.000000,3878.000000,1500.00000,798.000000,358.000000,102.000000,105.00000,345.000000,167.000000,...,2055.000000,153.000000,63.000000,40.500000,477.000000,117.00000,180.000000,70.000000,323.000000,143.000000
75%,624.000000,162.000000,5359.000000,2726.00000,1426.000000,568.000000,216.250000,160.00000,435.000000,510.000000,...,2983.000000,302.000000,97.000000,71.250000,849.000000,231.00000,542.000000,173.000000,445.000000,329.000000
max,4609.000000,1090.000000,70344.000000,18834.00000,8081.000000,5379.000000,13495.000000,7820.00000,1785.000000,15465.000000,...,16436.000000,3284.000000,13628.000000,1499.000000,7172.000000,1617.00000,12362.000000,3642.000000,1550.000000,5645.000000

In [57]:
missing_data = twitch_counts_df.isna().sum()
missing_data = missing_data[missing_data > 0]
missing_data.sort_values(ascending=False, inplace=True)
missing_data

250900     273
387990     244
2050650    240
945360     190
767560     127
2840770     51
1272080     43
602960      39
218620      21
784080      17
1229490     17
1363080     15
312520      15
1716740     10
284160       9
281990       8
613100       5
916440       5
1446780      4
2186680      4
1973530      4
287700       3
1144200      1
dtype: int64

In [58]:
for col in twitch_counts_df.columns:
    if col in missing_data[missing_data > 50].index:
        twitch_counts_df.drop(columns=[col], inplace=True)
    else:
        twitch_counts_df.ffill(inplace=True)

if twitch_counts_df.isna().sum().sum() > 0:
    twitch_counts_df.bfill(inplace=True)

In [59]:
missing_data = twitch_counts_df.isna().sum()
missing_data[missing_data > 0]

Series([], dtype: int64)

In [60]:
for col in player_counts_df.columns:
    if col not in twitch_counts_df.columns:
        player_counts_df.drop(columns=[col], inplace=True)

In [ ]:
review_sentiment = pd.read_csv('average_sentiment_reviews_daily.csv', index_col=0)
reddit_sentiment = pd.read_csv('average_sentiment_reddit_daily.csv', index_col=0)