## 3. Preparing the data for analysis and data exploration and visualization

### 3.1 Data cleaning and prep
This part of the project involves loading the data into structured tables, cleaning it for analysis and then later merging the tables together into one long form panel data table, that makes it easy and efficient to analyse. Main part of data cleaning involves checking again the time frame of the saved observations and removing unnecessary ones, renaming columns into more readable ones and dealing with missing data.

In [1]:
import pandas as pd
import os
import re
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
#Loading the names and appids of the analysed games
top_games = pd.read_csv('data/game_filtering/filtered_games_by_data.csv', sep=',')

In [ ]:
start_2025 = pd.to_datetime('2025-01-01')
end_2025 = pd.to_datetime('2025-12-31')

In [ ]:
#Loading the data for player counts, filtering observations based on the time frame and merging all the data into a single table

player_counts = []
folder = 'data/player_counts_2025'
for filename in os.listdir(folder):
    if filename.endswith('.csv'):
        df = pd.read_csv(os.path.join(folder, filename), index_col = 0, sep = ';')
        df.index = pd.to_datetime(df.index)
        appid = re.search(r'\d+', filename).group()
        df.rename(columns={"Players" : int(appid)}, inplace=True)
        df.drop(columns=['Average Players'], inplace=True)
        df = df.loc[(df.index >= start_2025) & (df.index <= end_2025)]
        player_counts.append(df)

player_counts_df = pd.concat(player_counts, axis=1)

,105600,107410,1085660,108600,1091500,1142710,1144200,1145360,1151340,1158310,...,739630,753640,767560,784080,892970,916440,945360,960090,961200,962130
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,36623.715068,13264.693151,36046.460274,30803.049315,44470.824658,29729.010959,10993.438356,5999.789041,11863.068493,24093.989041,...,23996.720548,1392.783562,1958.909589,1502.372603,31245.934247,6617.008219,8885.241096,11571.720548,2138.221918,6411.024658
std,6081.966448,2945.367462,16784.166160,8345.732673,12037.517250,6914.583815,6587.634218,3510.298148,2981.623984,7557.081044,...,6916.588069,324.877441,257.650468,696.784186,7525.420494,3824.754895,2325.584762,2771.561994,472.485505,2656.762059
min,24241.000000,8122.000000,12577.000000,20799.000000,24418.000000,21151.000000,4869.000000,2905.000000,7152.000000,17266.000000,...,13147.000000,873.000000,1325.000000,742.000000,18520.000000,2815.000000,4259.000000,7849.000000,1274.000000,2130.000000
25%,32135.000000,10978.000000,24488.000000,25007.000000,34417.000000,25195.000000,6996.000000,3801.000000,9968.000000,20311.000000,...,18348.000000,1158.000000,1768.000000,1013.000000,24922.000000,4295.000000,7404.000000,9682.000000,1802.000000,4319.000000
50%,36320.000000,12799.000000,30988.000000,28218.000000,43791.000000,27822.000000,8879.000000,4670.000000,11287.000000,22182.000000,...,22553.000000,1343.000000,1944.000000,1244.000000,30979.000000,5320.000000,8571.000000,10997.000000,2110.000000,5777.000000
75%,40934.000000,15076.000000,43899.000000,34194.000000,52779.000000,31747.000000,12479.000000,6829.000000,13041.000000,25189.000000,...,28544.000000,1610.000000,2147.000000,1803.000000,35769.000000,7272.000000,10428.000000,12598.000000,2468.000000,8078.000000
max,55462.000000,22317.000000,108535.000000,57886.000000,84236.000000,64399.000000,42490.000000,21221.000000,26373.000000,76719.000000,...,46942.000000,2538.000000,2762.000000,4603.000000,53576.000000,24689.000000,16298.000000,27736.000000,3502.000000,15266.000000

In [ ]:
#Checking the table for missing values
player_counts_df.isna().sum()

105600     0
107410     0
1085660    0
108600     0
1091500    0
          ..
916440     0
945360     0
960090     0
961200     0
962130     0
Length: 113, dtype: int64

There seems to be no missing data for the player counts table, therefore no further action is needed.

In [ ]:
#Loading the data for twitch viewership counts, filtering observations based on the time frame and merging all the data into a single table

twitch_counts = []
folder = 'data/2025_twitch_views'
for filename in os.listdir(folder):
    if filename.endswith('.csv'):
        df = pd.read_csv(os.path.join(folder, filename), index_col=0)
        df.index = pd.to_datetime(df.index, format = 'mixed')
        appid = re.search(r'\d+', filename).group()
        df.rename(columns={"value" : int(appid)}, inplace=True)
        df.drop(columns=['chans'], inplace=True)
        twitch_counts.append(df)

twitch_counts_df = pd.concat(twitch_counts, axis=1)

,105600,107410,1085660,108600,1091500,1142710,1144200,1145360,1151340,1158310,...,739630,753640,767560,784080,892970,916440,945360,960090,961200,962130
count,365.000000,365.000000,365.000000,365.00000,365.000000,365.000000,364.000000,365.00000,365.000000,365.000000,...,365.000000,365.000000,238.000000,348.000000,365.000000,360.00000,175.000000,365.000000,365.000000,365.000000
mean,622.468493,153.021918,4887.093151,2911.79726,1155.717808,497.049315,334.821429,183.79726,418.282192,516.391781,...,2652.227397,301.605479,144.172269,65.594828,899.117808,191.97500,579.582857,175.402740,390.841096,389.178082
std,858.982187,139.747769,5474.883863,3501.16570,1050.223665,458.101161,887.034083,487.82868,235.017476,1290.346671,...,2042.607115,454.800093,884.759916,92.909269,1093.923446,221.49846,1250.869708,329.830009,231.263127,697.802275
min,49.000000,33.000000,814.000000,482.00000,99.000000,87.000000,24.000000,25.00000,161.000000,24.000000,...,881.000000,28.000000,20.000000,19.000000,158.000000,20.00000,40.000000,21.000000,108.000000,23.000000
25%,183.000000,80.000000,2612.000000,1026.00000,496.000000,243.000000,62.000000,72.00000,288.000000,93.000000,...,1513.000000,93.000000,39.500000,28.000000,347.000000,59.75000,96.000000,47.000000,226.000000,74.000000
50%,306.000000,109.000000,3878.000000,1500.00000,798.000000,358.000000,102.000000,105.00000,345.000000,167.000000,...,2055.000000,153.000000,63.000000,40.500000,477.000000,117.00000,180.000000,70.000000,323.000000,143.000000
75%,624.000000,162.000000,5359.000000,2726.00000,1426.000000,568.000000,216.250000,160.00000,435.000000,510.000000,...,2983.000000,302.000000,97.000000,71.250000,849.000000,231.00000,542.000000,173.000000,445.000000,329.000000
max,4609.000000,1090.000000,70344.000000,18834.00000,8081.000000,5379.000000,13495.000000,7820.00000,1785.000000,15465.000000,...,16436.000000,3284.000000,13628.000000,1499.000000,7172.000000,1617.00000,12362.000000,3642.000000,1550.000000,5645.000000

In [ ]:
#Checking the table for missing data

missing_data = twitch_counts_df.isna().sum()
missing_data = missing_data[missing_data > 0]
missing_data.sort_values(ascending=False, inplace=True)
missing_data

250900     273
387990     244
2050650    240
945360     190
767560     127
2840770     51
1272080     43
602960      39
218620      21
784080      17
1229490     17
1363080     15
312520      15
1716740     10
284160       9
281990       8
613100       5
916440       5
1446780      4
2186680      4
1973530      4
287700       3
1144200      1
dtype: int64

There are some games with many missing observations. These will be dropped completely, because filling those observations artificially could alter the time series significantly. For games with less than 50 missing observations, which seems more reasonable for a 365 day analysis period, the backwards fill method will be used which fills missing observations with the value from their previous valid observation. This should not affect the final time series greatly, especially because after analysing the twitch_counts table itself it seems that the missing observations are spread throughout the whole time period and are not clustered together.

In [90]:
for col in twitch_counts_df.columns:
    if col in missing_data[missing_data > 50].index:
        twitch_counts_df.drop(columns=[col], inplace=True)
    else:
        twitch_counts_df.ffill(inplace=True)

if twitch_counts_df.isna().sum().sum() > 0:
    twitch_counts_df.bfill(inplace=True)

In [ ]:
#Checking if there is any remaining missing data left
missing_data = twitch_counts_df.isna().sum()
missing_data[missing_data > 0]

Series([], dtype: int64)

In [ ]:
#Making sure that games which have been dropped because of missing Twitch observations will also be dropped from the player counts table
for col in player_counts_df.columns:
    if col not in twitch_counts_df.columns:
        player_counts_df.drop(columns=[col], inplace=True)

In [ ]:
#Saving results for reproducibility
player_counts_df.to_csv('data/dataframes/player_counts_2025.csv')
twitch_counts_df.to_csv('data/dataframes/twitch_counts_2025.csv')

In [4]:
#Loading the results of sentiment analysis

review_sentiment = pd.read_csv('data/dataframes/average_sentiment_reviews_daily.csv')
reddit_sentiment = pd.read_csv('data/dataframes/average_sentiment_reddit_daily.csv')

In [5]:
player_counts_df = pd.read_csv('data/dataframes/player_counts_2025.csv', index_col=0)
twitch_counts_df = pd.read_csv('data/dataframes/twitch_counts_2025.csv', index_col=0)

### 3.2 Data exploration
This section includes the most important statistics for each table and exploring the data generally.

In [6]:
player_counts_df.describe()

,105600,107410,1085660,108600,1091500,1142710,1144200,1145360,1151340,1158310,...,703080,728880,739630,753640,784080,892970,916440,960090,961200,962130
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,36623.715068,13264.693151,36046.460274,30803.049315,44470.824658,29729.010959,10993.438356,5999.789041,11863.068493,24093.989041,...,4497.547945,8022.753425,23996.720548,1392.783562,1502.372603,31245.934247,6617.008219,11571.720548,2138.221918,6411.024658
std,6081.966448,2945.367462,16784.166160,8345.732673,12037.517250,6914.583815,6587.634218,3510.298148,2981.623984,7557.081044,...,1242.465420,2220.649369,6916.588069,324.877441,696.784186,7525.420494,3824.754895,2771.561994,472.485505,2656.762059
min,24241.000000,8122.000000,12577.000000,20799.000000,24418.000000,21151.000000,4869.000000,2905.000000,7152.000000,17266.000000,...,2717.000000,4556.000000,13147.000000,873.000000,742.000000,18520.000000,2815.000000,7849.000000,1274.000000,2130.000000
25%,32135.000000,10978.000000,24488.000000,25007.000000,34417.000000,25195.000000,6996.000000,3801.000000,9968.000000,20311.000000,...,3695.000000,6419.000000,18348.000000,1158.000000,1013.000000,24922.000000,4295.000000,9682.000000,1802.000000,4319.000000
50%,36320.000000,12799.000000,30988.000000,28218.000000,43791.000000,27822.000000,8879.000000,4670.000000,11287.000000,22182.000000,...,4258.000000,7557.000000,22553.000000,1343.000000,1244.000000,30979.000000,5320.000000,10997.000000,2110.000000,5777.000000
75%,40934.000000,15076.000000,43899.000000,34194.000000,52779.000000,31747.000000,12479.000000,6829.000000,13041.000000,25189.000000,...,4920.000000,8967.000000,28544.000000,1610.000000,1803.000000,35769.000000,7272.000000,12598.000000,2468.000000,8078.000000
max,55462.000000,22317.000000,108535.000000,57886.000000,84236.000000,64399.000000,42490.000000,21221.000000,26373.000000,76719.000000,...,10237.000000,17356.000000,46942.000000,2538.000000,4603.000000,53576.000000,24689.000000,27736.000000,3502.000000,15266.000000

In [7]:
player_counts_df.head()

,105600,107410,1085660,108600,1091500,1142710,1144200,1145360,1151340,1158310,...,703080,728880,739630,753640,784080,892970,916440,960090,961200,962130
DateTime,,,,,,,,,,,,,,,,,,,,,
2025-01-01,41202.0,15850.0,20665,56071.0,72131,41369,20524,7008,14873,28640,...,8087.0,9993.0,41930,2538.0,1471.0,46267,6547,13996,1621,9057
2025-01-02,49520.0,15563.0,18485,50638.0,64101,37165,17925,6847,12668,26706,...,7467.0,9398.0,40666,2293.0,1268.0,41601,5810,12970,1419,8616
2025-01-03,45238.0,16876.0,19561,50434.0,64650,37284,17286,6829,11972,26128,...,6886.0,10224.0,41429,2189.0,1214.0,42612,5746,12562,1486,8583
2025-01-04,47905.0,19760.0,21158,56159.0,70127,41360,17461,7093,13509,28204,...,7415.0,10370.0,45202,2241.0,1406.0,48115,6412,13542,1683,9073
2025-01-05,42731.0,19187.0,20975,57210.0,69948,40865,16504,6663,13790,27440,...,7402.0,8919.0,46942,2280.0,1460.0,50256,6663,13626,1696,8913

In [8]:
twitch_counts_df.describe()

,105600,107410,1085660,108600,1091500,1142710,1144200,1145360,1151340,1158310,...,703080,728880,739630,753640,784080,892970,916440,960090,961200,962130
count,365.000000,365.000000,365.000000,365.00000,365.000000,365.000000,365.000000,365.00000,365.000000,365.000000,...,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,622.468493,153.021918,4887.093151,2911.79726,1155.717808,497.049315,334.052055,183.79726,418.282192,516.391781,...,159.747945,137.268493,2652.227397,301.605479,65.624658,899.117808,194.180822,175.402740,390.841096,389.178082
std,858.982187,139.747769,5474.883863,3501.16570,1050.223665,458.101161,885.936737,487.82868,235.017476,1290.346671,...,460.370171,217.606483,2042.607115,454.800093,91.266690,1093.923446,231.444093,329.830009,231.263127,697.802275
min,49.000000,33.000000,814.000000,482.00000,99.000000,87.000000,24.000000,25.00000,161.000000,24.000000,...,24.000000,21.000000,881.000000,28.000000,19.000000,158.000000,20.000000,21.000000,108.000000,23.000000
25%,183.000000,80.000000,2612.000000,1026.00000,496.000000,243.000000,62.000000,72.00000,288.000000,93.000000,...,44.000000,50.000000,1513.000000,93.000000,28.000000,347.000000,59.000000,47.000000,226.000000,74.000000
50%,306.000000,109.000000,3878.000000,1500.00000,798.000000,358.000000,101.000000,105.00000,345.000000,167.000000,...,71.000000,72.000000,2055.000000,153.000000,41.000000,477.000000,116.000000,70.000000,323.000000,143.000000
75%,624.000000,162.000000,5359.000000,2726.00000,1426.000000,568.000000,216.000000,160.00000,435.000000,510.000000,...,125.000000,142.000000,2983.000000,302.000000,72.000000,849.000000,231.000000,173.000000,445.000000,329.000000
max,4609.000000,1090.000000,70344.000000,18834.00000,8081.000000,5379.000000,13495.000000,7820.00000,1785.000000,15465.000000,...,5938.000000,2106.000000,16436.000000,3284.000000,1499.000000,7172.000000,1617.000000,3642.000000,1550.000000,5645.000000

In [9]:
twitch_counts_df.head()

,105600,107410,1085660,108600,1091500,1142710,1144200,1145360,1151340,1158310,...,703080,728880,739630,753640,784080,892970,916440,960090,961200,962130
day,,,,,,,,,,,,,,,,,,,,,
2025-01-01,773,152,2103,12200,598,337,1356.0,114,421,503,...,130,60,2478,180,22.0,457,502.0,504,349,337
2025-01-02,750,154,2187,13515,1001,538,195.0,144,517,354,...,99,70,2695,530,22.0,561,301.0,57,336,359
2025-01-03,734,130,3600,13196,1929,392,432.0,84,398,830,...,85,74,2792,238,22.0,381,297.0,112,320,165
2025-01-04,618,247,3373,13438,4384,939,1084.0,62,404,1505,...,94,43,2098,518,24.0,468,231.0,60,379,266
2025-01-05,821,288,2513,12204,3069,427,1756.0,100,1165,1057,...,51,142,1819,133,37.0,457,293.0,75,370,198

In [10]:
review_sentiment.describe()

              appid  sentiment_binary
count  4.102100e+04      41021.000000
mean   9.991430e+05          0.904966
std    7.161345e+05          0.093094
min    5.700000e+02          0.000000
25%    3.743200e+05          0.860000
50%    9.164400e+05          0.920000
75%    1.384160e+06          0.970000
max    2.840770e+06          1.000000

In [11]:
review_sentiment.head()

   appid                 date  sentiment_binary
0    570  2025-01-01 00:00:00              0.93
1    570  2025-01-02 00:00:00              1.00
2    570  2025-01-03 00:00:00              0.99
3    570  2025-01-04 00:00:00              0.92
4    570  2025-01-05 00:00:00              0.93

In [12]:
reddit_sentiment.describe()

         Unnamed: 0         appid  sentiment_binary    post_count
count  36748.000000  3.674800e+04      36748.000000  36748.000000
mean   18373.500000  9.959059e+05          0.810696    134.971291
std    10608.378183  7.127362e+05          0.086173    351.082612
min        0.000000  5.700000e+02          0.000000      1.000000
25%     9186.750000  3.771600e+05          0.760000     32.000000
50%    18373.500000  9.164400e+05          0.810000     64.000000
75%    27560.250000  1.384160e+06          0.870000    121.000000
max    36747.000000  2.840770e+06          1.000000  10482.000000

In [13]:
reddit_sentiment.head()

   Unnamed: 0  appid        date  sentiment_binary  post_count
0           0  570.0  2025-01-01              0.74         129
1           1  570.0  2025-01-02              0.85         149
2           2  570.0  2025-01-03              0.83         168
3           3  570.0  2025-01-04              0.82         148
4           4  570.0  2025-01-05              0.80         158

### 3.3 Merging all data into one dataframe for panel data
In order to form one table with all the data in the form of panel data, the tables need to be prepared appropriately. Because the player_counts and twitch_counts tables have data for each game in separate columns they need to be converted to long form data, columns are renamed to be more readable and appropriate for merging and the dates are normalized to midnight to avoid problems with grouping.

In [ ]:
#Cleaning all the tables

player_counts_df.reset_index(inplace=True)
twitch_counts_df.reset_index(inplace=True)
player_counts_df.rename(columns={'DateTime': 'date'}, inplace=True)
twitch_counts_df.rename(columns={'day': 'date'}, inplace=True)

player_counts_df = player_counts_df.melt(id_vars='date', var_name='appid', value_name='player_count')
twitch_counts_df = twitch_counts_df.melt(id_vars='date', var_name='appid', value_name='twitch_count')

review_sentiment.rename(columns={'sentiment_binary': 'review_sentiment'}, inplace=True)
reddit_sentiment.rename(columns={'sentiment_binary': 'reddit_sentiment'}, inplace=True)

player_counts_df['appid'] = player_counts_df['appid'].astype(int)
twitch_counts_df['appid'] = twitch_counts_df['appid'].astype(int)
review_sentiment['appid'] = review_sentiment['appid'].astype(int)
reddit_sentiment['appid'] = reddit_sentiment['appid'].astype(int)

player_counts_df['date'] = pd.to_datetime(player_counts_df['date']).dt.normalize()
twitch_counts_df['date'] = pd.to_datetime(twitch_counts_df['date']).dt.normalize()
review_sentiment['date'] = pd.to_datetime(review_sentiment['date']).dt.normalize()
reddit_sentiment['date'] = pd.to_datetime(reddit_sentiment['date']).dt.normalize()

C:\Users\magda\AppData\Local\Temp\ipykernel_41608\524765352.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  player_counts_df.reset_index(inplace=True)
C:\Users\magda\AppData\Local\Temp\ipykernel_41608\524765352.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  twitch_counts_df.reset_index(inplace=True)

In [ ]:
#Merging all the tables using inner join, to avoid missing data and keep in mind some games were dropped because of missing data earlier

panel_data = pd.merge(player_counts_df, twitch_counts_df, on=['date', 'appid'], how='inner')
panel_data = pd.merge(panel_data, review_sentiment[['date', 'appid', 'review_sentiment']], on=['date', 'appid'], how='inner')
panel_data = pd.merge(panel_data, reddit_sentiment[['date', 'appid', 'reddit_sentiment', 'post_count']], on=['date', 'appid'], how='inner')
panel_data = pd.merge(panel_data, top_games[['appid', 'name']], on='appid', how='inner')
panel_data = panel_data[['date', 'appid', 'name', 'player_count', 'twitch_count', 'review_sentiment', 'reddit_sentiment', 'post_count']]
panel_data.sort_values(by=['appid', 'date'], inplace=True)
panel_data.reset_index(drop=True, inplace=True)

panel_data.head()

,date,appid,name,player_count,twitch_count,review_sentiment,reddit_sentiment,post_count
0,2025-01-01,570,Dota 2,638080.0,24898.0,0.93,0.74,129
1,2025-01-02,570,Dota 2,648021.0,27474.0,1.00,0.85,149
2,2025-01-03,570,Dota 2,686353.0,34790.0,0.99,0.83,168
3,2025-01-04,570,Dota 2,710477.0,33816.0,0.92,0.82,148
4,2025-01-05,570,Dota 2,695257.0,33035.0,0.93,0.80,158

In [ ]:
#Saving the table for reproducibility
panel_data.to_csv('data/dataframes/panel_data_2025.csv', index = False)

### 3.3 Data Visualization
To explore the data further, after preparing it in panel data form, this section focuses on creating visualizations using plotly. Because there are about 100 games in the analysis scope, some graphs are less readable, which is why plotly graphs were used, as they are more interactive.

In [ ]:
plt.style.use('seaborn-v0_8-darkgrid')

In [ ]:
fig = px.line(panel_data, x='date', y='reddit_sentiment', color='name', title='Reddit Sentiment Over Time')
fig.show()

In [ ]:
fig = px.line(panel_data, x='date', y='player_count', color='name', title='Player Count Over Time')
fig.show()

In [ ]:
fig = px.line(panel_data, x='date', y='twitch_count', color='name', title='Twitch Count Over Time')
fig.show()

In [ ]:
fig = px.line(panel_data, x='date', y='review_sentiment', color='name', title='Review Sentiment Over Time')
fig.show()

In [ ]:
fig = px.line(panel_data, x='date', y='post_count', color='name', title='Posts Count Over Time')
fig.show()

In [ ]:
# g = sns.FacetGrid(panel_data, col="name", col_wrap=6, height=3, aspect=1.5)
# g.map(sns.lineplot, "date", "smoothed_sentiment")
# g.set_titles(col_template="{col_name}")
# plt.tight_layout()
# plt.show()